### ISSUE TITLE
Track Donation Statistics for Endaoment Projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#13]
In our current analytics dashboard we should be able to filter the amount of donors, donations and the total donation value to only Endaoment projects between two periods of time.

Analytics Dashboard: https://stats.giveth.io/
Staging: https://staging.stats.giveth.io/

This can be added as a checkbox option on the associated section on the analytics dashboard

to be clear, I am referring to these 3 queries: 

![Image](https://github.com/Giveth/analytics-dashboard/assets/67759413/7c9453bb-7319-4fc6-a684-664aad310d44)

**Comment by divine-comedian** [comment]
@Reshzera can you work on this one with assistance from @mohammadranjbarz ?

**Comment by divine-comedian** [comment]
@mohammadranjbarz - can you pick this one up when you finish zkEVM and DeVouch / Decentralized Verification items?

**Comment by mohammadranjbarz** [comment]
@HrithikSampson  Can you work on this?

**Comment by mohammadranjbarz** [comment]
@geleeroyale Can you give access to this project to @HrithikSampson?

**Comment by HrithikSampson** [comment]
Thanks @geleeroyale

**Comment by divine-comedian** [comment]
FE repo for analytics dashboard - https://github.com/Giveth/analytics-dashboard

**Comment by divine-comedian** [comment]
@HrithikSampson what is the update on this issue?

**Comment by HrithikSampson** [comment]
@divine-comedian I was waiting for review after adding the test cases I had again rerequested it for review after adding the test cases. Can I merge it, Since I already had got the review once I am able to merge it.

**Comment by divine-comedian** [comment]
Thanks! Looks like it's ready to merge - please update once it's ready for testing.

**Comment by HrithikSampson** [comment]
@maryjaf @LatifatAbdullahi , this issue is ready to be tested

**Comment by HrithikSampson** [comment]
@LatifatAbdullahi @maryjaf , this issue is ready to be tested

**Comment by LatifatAbdullahi** [comment]
@HrithikSampson @divine-comedian 

**Test Update** on staging 

Donors Count:

Optimism Sepolia - **Pass**
Base Sepolia - **Pass**

Donations count:

Optimism Sepolia - **Pass**
Base Sepolia - **Pass**

Total Donations :

Optimism Sepolia - **Pass**
Base Sepolia - **Pass**

**Comment by divine-comedian** [comment]
@HrithikSampson looks like this passed QA 

Can you let me know which repositories need a release to make this feature go live on production?

**Comment by HrithikSampson** [comment]
@divine-comedian , impact-graph for backend and Analytics Dashboard for the Frontend

> @HrithikSampson looks like this passed QA
> 
> Can you let me know which repositories need a release to make this feature go live on production?

**Comment by divine-comedian** [comment]
@HrithikSampson - can we make this feature go to production?

**Comment by HrithikSampson** [comment]
yes @divine-comedian , since staging is merged to production then this can also be merged to production

**Comment by divine-comedian** [comment]
okay, did you do it @HrithikSampson - that is my question

**Comment by HrithikSampson** [comment]
I have merged it now @divine-comedian

**Comment by LatifatAbdullahi** [comment]
Thanks @HrithikSampson 

**Test Update on Production**  @divine-comedian 



Donors Count:

Optimism - **Pass**
Base - **Pass**

Donations count:

Optimism  - **Pass**
Base - **Pass**

Total Donations :

Optimism - **Pass**
Base - **Pass**
