### ISSUE TITLE
Track recurring donation statistics 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#22]
We should be able to query and track the following information related to recurring donations feature: 

- total USD value of all recurring donations between two dates
- total USD value of all recurring donations made in a specific token between two dates
- count of active recurring donations created between two dates
- count of active recurring donations made with a speicfic token created between two dates

This information should be available through https://stats.giveth.io/

**Comment by divine-comedian** [comment]
Hey guys - this issue is not completed. I specified this information should be made available on the giveth analytics website https://stats.giveth.io/

I was informed only the query has been made so we need to make sure that this query can be ran from the aforementioned site and return the expected information.

**Comment by maryjaf** [comment]
> Hey guys - this issue is not completed. I specified this information should be made available on the giveth analytics website https://stats.giveth.io/
> 
> I was informed only the query has been made so we need to make sure that this query can be ran from the aforementioned site and return the expected information.

Sorry, in fact, I had not seen this condition, unfortunately
And I just checked the response API response

**Comment by Meriem-BM** [comment]
Hey @divine-comedian just to make sure, user can filter by "Token" if so, we might need to add a dropdown filter, I see only by Network Id.

**Comment by divine-comedian** [comment]
@Meriem-BM - we don't need to allow the user to filter the query by token ID - if it's possible without much effort that's a nice bonus feature. 

However there should be a way with one query to get the total values across all possible tokens.

Currently we only support one chain - Optimism - for recurring donations and we don't have plans at this moment to add more network support. but we might at sometime in the future.

**Comment by Meriem-BM** [comment]
@maryjaf this issue is ready for test you can check here https://staging.stats.giveth.io

**Comment by maryjaf** [comment]
Since Latifat was working on analytics dashboard , Do you have time to take it ? @LatifatAbdullahi

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @Meriem-BM 
**Test Update**

Recurring donation count: **Pass**
Total Recurring donations: **Fail**


Its keeps throwing this error

![image](https://github.com/user-attachments/assets/f34ff603-7056-45f7-bee9-f2b44fba57f6)



![image](https://github.com/user-attachments/assets/837d0310-f28e-4b67-a20f-d2c4734e0086)



![cn](https://github.com/user-attachments/assets/a8f5da9c-95cb-4448-a89f-a3825ad037a7)


![1t](https://github.com/user-attachments/assets/7f2de4c2-0570-4f87-99d7-66b4be2bf788)
