### ISSUE TITLE
projects count stats are incorrect

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#34]
Testing the Projects Count feature on https://stats.giveth.io/ appear to be incorrect. 

Checking the count of projects we can see on the dapp it says we have 2812 listed project - but on the analytics dashboard it says we have 2914 - which one is correct? They should be the same number... 

![Image](https://github.com/user-attachments/assets/a6ff801f-1477-4782-a483-5a0d64235633)

We should also add an option to "exclude externally imported projects" this would be a checkbox that would exclude projects we've imported from another app such as The Giving Block, Change.org or Endaoment.

When the box is checked we should then exclude those projects and show only Giveth projects that have been created directly on our platform

**Comment by ae2079** [comment]
@divine-comedian 
As I should spend all of my capacity on the Qacc project, I can not do this issue in the next 6 weeks, so I unassigned this issue from myself

**Comment by RamRamez** [comment]
@Reshzera could you please take this issue?
cc @jainkrati

**Comment by Reshzera** [comment]
@RamRamez Sure

**Comment by RamRamez** [comment]
@Reshzera investigated and noticed that on all projects page we fetch only active projects but on analytics dashboard we fetch them all.
@divine-comedian is it ok to change the analytics dashboard to show only active projects?

**Comment by divine-comedian** [comment]
Got it, so the projects count in analytics is counting deactivated and cancelled projects.. 

let's go ahead and make your suggested changes @RamRamez - and rename the query header text to "Active Projects Count"

**Comment by RamRamez** [comment]
@Reshzera I've commented on your PR, it needs a tiny change, please fix it, also in [analytics-dashboard](https://github.com/Giveth/analytics-dashboard) please change the title of "Projects Count" to "Active Projects Count"

**Comment by divine-comedian** [comment]
@Reshzera what is the update on this issue?

**Comment by Reshzera** [comment]
@divine-comedian I didn't have seen this comment, I'm sorry. I'll fix it

**Comment by maryjaf** [comment]
@LatifatAbdullahi Can you please pick this up?

**Comment by LatifatAbdullahi** [comment]
Test Udpdate

**Stage**

This works as expected on Stage

![ex](https://github.com/user-attachments/assets/8a74264b-70ff-4be5-8e8e-58d44e5f67da)
![inm](https://github.com/user-attachments/assets/3236563b-1afe-4584-ba2b-d2d51a604734)



The title has also been updated to **Active Project Counts**

![ac](https://github.com/user-attachments/assets/5717896b-d793-47af-93d0-d9e8e0342a46)
