### ISSUE TITLE
recurring donations stats tracking is INCORRECT

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#42]
looking on https://stats.giveth.io/ it appears that the values being returned are being underestimated, we should investigate why these numbers are wrong and fix the queries as needed.

In order to compare numbers I ran the stats query against the numbers I could find in the givbacks queries, particularly for [eligible-donations between two given dates ](https://givbacks.giveth.io/api-docs/#/default/get_eligible_donations)

I posted a couple of the response CSV files in this sheet here and filtered for only recurring donations then retried the sum of the usd values.
https://docs.google.com/spreadsheets/d/1hRaX5arccD0XGmJO8xAaGZK0qeEesCqHuu-982HTyTI/edit?usp=sharing

### Recurring Donations Count

According to the stats dashboard there has been only 88 recurring donation streams made, however according to the eligible-donations `parentRecurringDonationId` there are 213 parent recurring donations. 

Does this mean there is actually 213 unique donation streams that have been made? If so then the number 88 given by the stats dashboard seems VERY off.

### Recurring Donations Value

In the stats dashboard from July 2024 until present it says we have had around $921 in recurring donations. When I retrieved the usd value of givbacks eligible recurring donations for the same period it was $1186 - a very notable difference!

**Comment by divine-comedian** [comment]
@Meriem-BM since it looks like you worked on this in https://github.com/Giveth/analytics-dashboard/issues/22 can you please take some time to investigate why this isn't working as expected? 

FYI @mohammadranjbarz

**Comment by CarlosQ96** [comment]
@divine-comedian  moved to qa, let me know if all good

**Comment by divine-comedian** [comment]
The recurring donation counts seems to be working as expected now. 

However the total USD value still seems to be off. Looking at the stats dashboard it says from 2024-07-01 there was only $935 worth of recurring donations made. 

When querying the same period of givbacks eligible recurring donations from the givbacks-calculation API we get around $1759 - what could be causing this massive difference? 

![Screenshot 2024-11-06 221649](https://github.com/user-attachments/assets/8d900883-c2b9-4531-accc-763bfa166378)
![Screenshot 2024-11-06 222217](https://github.com/user-attachments/assets/93bea4cd-9c37-4cd5-89d5-e0e0a06f4bfd)

**Comment by CarlosQ96** [comment]
@divine-comedian Could I have access to the spreadsheet, ill validate the calculations tomorrow.

**Comment by divine-comedian** [comment]
It should already be open for comment access by anyone - try this link

https://docs.google.com/spreadsheets/d/1hRaX5arccD0XGmJO8xAaGZK0qeEesCqHuu-982HTyTI/edit?usp=drivesdk

**Comment by CarlosQ96** [comment]
I checked the mini donations saved in the db, on the donation table and the values are 1742-1761 USD depending on conditions which makes sense with your sum of donations.

But the query we currently use is the recurringDonation "parent" total USD. So I think there is a bug on updating the recurring donation total usd value based on the mini donations. 
I'll Work on this tomorrow mostly investigated it.

**Comment by CarlosQ96** [comment]
@divine-comedian

**Comment by CarlosQ96** [comment]
@divine-comedian in staging will release later today this as a hotfix.

**Comment by CarlosQ96** [comment]
@divine-comedian deployed

**Comment by divine-comedian** [comment]
Checking it out on production https://stats.giveth.io/ when I search from nov 1 2024 until present it says there is over $1300 in USD value

While when I look in the eligible donations givbacks data it says there is only $56 usd value of recurring donations - which seems more reasonable. 

![image](https://github.com/user-attachments/assets/10ffe697-811b-4757-8ff2-f4964d15f2d0)

![image](https://github.com/user-attachments/assets/2ba14bda-5797-456b-b02b-4f5a5be92606)


So it seems something is still not being calculated correctly by the query.

**Comment by CarlosQ96** [comment]
@divine-comedian I see the issue, it's I am seeing the recurring donation as a whole with the query. I am not filtering by mini donations. 
Ill have to change the query then to use the mini donations for the stats instead of the parent.

I'll do that change.

**Comment by divine-comedian** [comment]
Testing the count it appears to be off as well

Checking on the stats dashboard between july 1 - nov. 3 it claims to have had a count of 87 givbacks eligible recurring donations 

![image](https://github.com/user-attachments/assets/90dfc87a-4f8b-46f0-a11c-7eaf20cfa6ce)


while if we check in the givbacks data for eligible-donations I used COUNTUNIQUE to find the number of unique parentRecurringDonation IDs returned for the same period of time it says there was 119 active, givbacks eligible recurring donations streams 

![image](https://github.com/user-attachments/assets/cb660df9-df3d-4587-95bd-186d0829f29e)

**Comment by CarlosQ96** [comment]
@divine-comedian I am getting more donations from those dates from the database.
Is there a reason for the difference? or are some donations removed from sybil? 

Can we look over the data and queries tomorrow if you have a chance?

**Comment by CarlosQ96** [comment]
@divine-comedian  Merged latest changes, can check.

**Comment by divine-comedian** [comment]
Thanks Carlos, based on our convo the numbers look pretty accurate, assuming this is already pushed to production I think we can close this issue. 

Is there anything else that needs to be done?

**Comment by CarlosQ96** [comment]
Yes is on production ! we can close this issue
