### ISSUE TITLE
Allow to set date ranges by days instead of months

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#6]
For several queries it would be much better if we could set the date ranges by day instead of month, this will help us track things like 

- Donations/Donors within GIVbacks round
- Donor/Project stats within a WG Season

This applies to the following queries: 

- [x] Projects Count
- [x] Donors Count
- [x] Donations Count
- [x] Total Donations ($)
- [x] New Donors Count
- [x] New Donors Donation total USD

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by divine-comedian** [comment]
@maryjaf what is the status of this issue?

**Comment by maryjaf** [comment]
Unfortunately, I did not complete the test related to analytical tasks
I'll do it this week

**Comment by maryjaf** [comment]
> * Projects Count
> * [x]  Donors Count
> * [x]  Donations Count
> * [x]  Total Donations ($)

for these 4 items the user could set date 
but I haven't seen these 2 items in dashboard
 New Donors Count
 New Donors Donation total USD
 @RamRamez

**Comment by RamRamez** [comment]
> > * Projects Count
> > * [x]   Donors Count
> > * [x]   Donations Count
> > * [x]   Total Donations ($)
> 
> for these 4 items the user could set date but I haven't seen these 2 items in dashboard New Donors Count New Donors Donation total USD @RamRamez

@divine-comedian we don't have these two items but I've added date ranges by days to all queries

**Comment by RamRamez** [comment]
> > * Projects Count
> > * [x]   Donors Count
> > * [x]   Donations Count
> > * [x]   Total Donations ($)
> 
> for these 4 items the user could set date but I haven't seen these 2 items in dashboard New Donors Count New Donors Donation total USD @RamRamez

my bad, those two queries were only on staging BE that time so I deactivated them on production to prevent errors, now I added them back to production

**Comment by maryjaf** [comment]
I haven't access to this project to move it to done @RamRamez @divine-comedian

**Comment by RamRamez** [comment]
> I haven't access to this project to move it to done @RamRamez @divine-comedian

I gave you access, could you please check again?
