### ISSUE TITLE
Allow to filter Donation data by verified project donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#7]
For these two queries: 

- [x] Donations Count 
- [x] Total Donations ($)

It would be nice to have a toggle that allows us to check for only donations that went to verified projects in between the specified date ranges.

**Comment by RamRamez** [comment]
@maryjaf to test and verify
You can test it on staging with [this link](https://analytics-dashboard-git-allow-to-filter-donatio-95a239-givethio.vercel.app/)
After SuperFluid release, you test it on production (stats.giveth.io)

**Comment by divine-comedian** [comment]
@RamRamez  

I still haven't seen these options added in to production 
![image](https://github.com/Giveth/analytics-dashboard/assets/67759413/dc344694-874b-46b7-a470-3d5dfe722372)


What's the status here?

**Comment by RamRamez** [comment]
@divine-comedian thanks for reminding me, I merged the PR and now it can be tested on production.

**Comment by divine-comedian** [comment]
tested in production and looks to be working! closing this one.
